import { writeFileSync } from 'node:fs';
const rows = ['; Generated by tools/sine.mjs. Signed Q8.8 values, degrees 0..359.', 'sine_table:'];
for (let angle = 0; angle < 360; angle += 12) {
  rows.push('    defw ' + Array.from({ length: 12 }, (_, i) => Math.round(256 * Math.sin((angle + i) * Math.PI / 180))).join(','));
}
writeFileSync(new URL('../build/sine.inc', import.meta.url), rows.join('\n') + '\n');
